project:
  type: website
  output-dir: docs

website:
  title: "made in Quarto"
  sidebar: 
    search: true
  navbar:
    logo: ofce.png
    right: 
      - text: EN
        href: index_EN.qmd
      - href: https://www.ofce.sciences-po.fr/
      - icon: rss
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/OFCE/Blog-OFCE-Beta
      - icon: twitter
        href: https://twitter.com/ofceparis
      - icon: linkedin
        href: https://www.linkedin.com/company/le-golvan/?originalSubdomain=fr
format:
  html:
    theme:
      light: litera
      dark: [darkly, theme-dark.scss]

editor: visual

