project:
  type: website
  output-dir: docs

website:
  title: "Blog de l'OFCE, une proposition basé sur quarto"
  sidebar: 
    search: true
  navbar:
    logo: ofce.png
    right:
      - about.qmd
      - icon: github
        href: https://github.com/OFCE/Blog-OFCE-Beta
      - icon: twitter
        href: https://twitter.com/ofceparis
format:
  html:
    theme: litera
    css: styles.css

editor: visual

